spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db5
    username: root
    password: Mantu@12
    driver-class-name: com.mysql.cj.jdbc.Driver
