version: "3.8"

services:
  app:
    image: docker_image/testapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db5
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Mantu@12
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: db5
      MYSQL_USER: admin
      MYSQL_PASSWORD: Mantu@12
      MYSQL_ROOT_PASSWORD: Mantu@12
    ports:
      - "3307:3306"
